version: "3"

services:
  mongo:
    user: "999:999"
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/data/db

volumes:
  data:
